version: "3.8"

services:
  photoupload:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        USE_LOCAL: "true"
    ports:
      - "3500:3500" # Expose the backend API
    environment:
      - MONGO_URI=mongodb://mongo:27017/photos
    depends_on:
      - mongo
      - fluentd
    networks:
      - monitoring_network
    volumes:
      - ./uploads:/app/backend/uploads
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "fluentd:24224"
        tag: "photoupload_app"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo_data:/data/db
    networks:
      - monitoring_network
    logging:
      driver: "none"

  fluentd:
    build:
      context: .
      dockerfile: ./fluentd/Dockerfile # Make sure this refers to the correct Dockerfile
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./fluentd/logs:/fluentd/logs
    networks:
      - monitoring_network
    environment:
      FLUENTD_CONF: fluent.conf
    # user: root # Ensure fluentd runs as root when installing the gem
    # command: sh -c "gem install fluent-plugin-mail && fluentd -c /fluentd/etc/fluent.conf"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    networks:
      - monitoring_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge
